### ISSUE TITLE
"Open file" bugs

### ISSUE THREAD

**Issue by silverwings15** [ilse-langnar/notebook#1]
- Both these buttons seem to have the same name and function 
![image](https://user-images.githubusercontent.com/10742312/168725119-ea3bf8de-7591-4995-ac8f-ac0846aa4869.png)
![image](https://user-images.githubusercontent.com/10742312/168725175-186e703a-e4fa-4968-8a16-30f669ac702a.png)

- Clicking on either of them creates a new item. when you try to rename this item, a popup appears saying the item cannot be found
![image](https://user-images.githubusercontent.com/10742312/168725343-5b5acbb3-b1e7-49fc-b31a-f937c82fb1a7.png)

- Trying to delete the item by pressing the trash icon has no effect
![image](https://user-images.githubusercontent.com/10742312/168725384-b013c4a1-cddb-4753-8356-3586ae36fdc4.png)

**Comment by ilse-langnar** [comment]
Anything Else?

**Comment by ilse-langnar** [comment]
Both these buttons seem to have the same name and function
Fixed
https://github.com/ilse-langnar/notebook/commit/30eb0ef132bb484ceacb3bc12e9c829d8b4ea802
