### ISSUE TITLE
"Add menu" bug

### ISSUE THREAD

**Issue by silverwings15** [ilse-langnar/notebook#2]
The add menu button doesn't seem to do anything aside from collapsing elements with no way to get them to show again except by restarting the program. This is what happens when I click it multiple times

Before clicking:

![image](https://user-images.githubusercontent.com/10742312/168725882-ec8221ce-475c-409c-836d-9de77006dfd2.png)

First click:
![image](https://user-images.githubusercontent.com/10742312/168725916-25ec33b9-ff40-4473-9b87-ba63aa59db36.png)

Second click
![image](https://user-images.githubusercontent.com/10742312/168725923-8baf500f-4405-4418-8bda-57b8c7df09a3.png)

Third click
![image](https://user-images.githubusercontent.com/10742312/168725941-b998753c-9e9e-4cc2-bab7-1026768a7f9c.png)

**Comment by ilse-langnar** [comment]
It was a small logic error FIXED
https://github.com/ilse-langnar/notebook/commit/78072277446d825186365f911679ef1a07261eba

closing
