### ISSUE TITLE
Unable to delete content in an item

### ISSUE THREAD

**Issue by silverwings15** [ilse-langnar/notebook#3]
![image](https://user-images.githubusercontent.com/10742312/168726416-8e1f7ecd-90d6-4fba-ab47-f4b9aa962d4c.png)

**Comment by ilse-langnar** [comment]
Use the second button from your mouse.

**Comment by ilse-langnar** [comment]
I'll add to the tutorial, this app relies heavily on combination like shift+click, ctrl+ctrl etc.
