### ISSUE TITLE
Discord invitation link is invalid

### ISSUE THREAD

**Issue by ajoual** [ilse-langnar/notebook#4]
The discord link (https://discord.com/invite/9BVx8YHr) provided in the Readme and on the app landing page is invalid.

**Comment by ilse-langnar** [comment]
Thank you.
Fixed.
[https://github.com/ilse-langnar/notebook/commit/e8af5247ddcfa4cf325aa68b2d21263faf0d7a69#diff-29883509755eacc0947b0b6e71f0c1b4f39a291d896ca227a828f9d53c6ffaddR43-L41 #](https://github.com/ilse-langnar/notebook/commit/e8af5247ddcfa4cf325aa68b2d21263faf0d7a69)

**Comment by vasnt** [comment]
none of these link work:
https://discord.gg/9BVx8YHr 
https://discord.gg/dAKGGTXY

**Comment by ilse-langnar** [comment]
I think discord is nuking my links ... bruh.

**Comment by ilse-langnar** [comment]
https://discord.gg/4MC26m87Dp

**Comment by vasnt** [comment]
it needs be updated at below also on gihub.
" I'll post updates, ideas, plugins, themes, snippets, commands screenshots and more. https://discord.gg/dAKGGTXY "

Discord is a good way to build community & discuss further, so you may update description accordingly.
