### ISSUE TITLE
Windows app Issues

### ISSUE THREAD

**Issue by vasnt** [ilse-langnar/notebook#7]
I downloaded windows exe app, But after opening app, it is not possible to make any note or see any notes in folder. 
Other functionality like web/srs is also not working yet. 

Is still app not functional?

**Comment by ilse-langnar** [comment]
> Is still app not functional?

I'm working on finishing those issues, it's supposed to be a browser + note-manager + filesystem all in one.
I'm working on trying to sandbox the API so it's safer. I'll release another version soon.



> But after opening app, it is not possible to make any note or see any notes in folder.

Can you show me a screenshot?

**Comment by vasnt** [comment]
- <img width="956" alt="image" src="https://user-images.githubusercontent.com/117589240/208486951-2187559d-54ad-4647-809a-0715661328d0.png">
- 
- <img width="960" alt="image" src="https://user-images.githubusercontent.com/117589240/208487015-36c8ab62-5393-44a5-bffb-c4db1893f6e7.png">

I think screenshots cant help
Need to have video/screencast.

**Comment by vasnt** [comment]
could you add (user-friendly) tabular support (like coda/notion/airtable etc.) as well?

**Comment by ilse-langnar** [comment]
I will eventually ty.
